### ISSUE TITLE
metadata problems after union

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#158]
This isn't a huge problem but `union` is creating extra (different) entries in `@metadata` that seem to be related to either the first or last SPC that was combined. Fortunately, getting / setting list elements by name always works on the first instance of a label--so no apparent problems.

```r
library(aqp)

z <- lapply(1:10, random_profile, SPC=TRUE)
z <- union(z)

m <- metadata(z)

table(names(m))
```

**Comment by brownag** [comment]
Thanks for pointing this out.

After a relatively recent update, the metadata are created in the first instance positions by `depths<-` 

Now that union uses depths, sorting and "correct" or "standard" construction of an SPC is now implicit in all union-ing, as you had originally suggested a couple weeks back.

The correct metadata are constructed when the SPC is constructed via `depths<-`. `union` accounts for user-level customizations such as the data.frame subclass being used, `group_by` metadata, etc so that does not need to be specifically accounted for in the line of code that was bugged/fixed.

**Comment by dylanbeaudette** [comment]
Thanks!
