### ISSUE TITLE
Forthcoming release of sp/rgdal will need aqp release

### ISSUE THREAD

**Issue by rsbivand** [ncss-tech/aqp#166]
The current status of rsbivand/sp and rgdal on R-Forge wth released PROJ/GDAL breaks released aqp, but because some tests are commented out in master, it passes check. Just a heads up that an aqp release may/will be needed to get around this problem.

**Comment by brownag** [comment]
Thanks for the heads up on these changes -- we are making progress towards [an overdue] release so this is timely.

I believe I was the one who added the rgdal version-checking to those tests ... and ultimately commented them out. When given a "legacy" proj4 string, some of our expectations for result of the `proj4string,SoilProfileCollection-method` needed updating. Ideally we would not have those tests commented out -- but I was having issues that I did not fully understand. 

Today I re-read your blog post and inspected a bit more ... I think I "solved" the broken tests in test-SPC-object.R: 1e55ad986839c09bfe3cfce16f1b2c63b7c9bbb8

With these changes ncss-tech/aqp@master tests appear OK with rgdal 1.5-17 (r-forge), 1.5-16 (cran), 1.5-10 (https://github.com/cran/rgdal/commit/ec3b6d5f4104a6d5ce29479a2ca0d8b915073c0c) and 1.4-8 (https://github.com/cran/rgdal/commit/e5bee698c8cd2dd4f1c22236653c23fe1663c261).

**Comment by rsbivand** [comment]
Thanks for the update. I can't comment on the unauthorized github mirror of **rgdal**, which do not show whether the chosen points are releases as in the CRAN rgdal archive, specific SVN revision numbers, or what. Links to the CRAN archive are meaningful, to github much less so because I'd have to link through to see what you mean. Further, did you check with  the same versions of PROJ/GDAL, or with different versions? Three levels perhaps worth considering are PROJ 5.2.0/GDAL 2.2.4 (oldrelease MacOS); PROJ 6.3.1/GDAL 3.0.4 (CRAN Windows binary) and current PROJ 7.1.1/GDAL 3.1.3 (source installs only). Which were you using?

**Comment by brownag** [comment]
OK. For what it is worth, those are the GitHub commits that correspond to the version releases of **rgdal** that I noted.

I will investigate the PROJ/GDAL binaries a bit further... but I think we are OK.

The tests that were breaking had to do with the possible GDAL/OSR exportToProj4() degradation warnings. But I don't think any of the changes meaningfully affect us -- they just affect tests due to warnings, messages, and changes in how legacy proj strings are handled.

In principle there is no reason why PROJ/GDAL "breaks" aqp other than the exact string matching of the PROJ4 strings -- which has been a moving target and source of [some of] my confuson. Thanks for following up.

**Comment by brownag** [comment]
I now have successfully tested {aqp} with {rgdal} 1.5-8+, including 1.5-17 (r-forge) built w/ PROJ 7.11/GDAL 3.1.3 with R 4.0.2 / Ubuntu 20.04. All testing above was done w/ PROJ 6.3.1/GDAL 3.0.4 windows binaries or pre-compiled Debian packages.

**Comment by rsbivand** [comment]
Thanks, 1_24 also passes check for me locally, with development versions of sp and rgdal, PROJ 7.1.1 and GDAL 3.1.3.
