### ISSUE TITLE
site(d) <- results in corrupt profiles

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#171]
For some reason the NEON data once converted into an SPC does not play nicely with:
```r
subset(S, siteID %in% c('SJER', 'SOAP', 'TEAK'))
```
There is a lot of "magic" involved with getting the NEON data into R, resulting in a global environment full of objects. Also, the final object `S` contains many duplicated columns resulting from joins.

This has nothing to do with `aqp::subset`, rather novel input data and `site(x) <-`.

Setup:
```r
# Load required packages
library(neonUtilities)
library(aqp)
library(dplyr)

## ----download-data, results='hide'--------------------------------------------------------------------

MP <- loadByProduct(dpID = "DP1.00096.001", check.size = F)

# Unlist to environment - see download/explore tutorial for description
list2env(MP, .GlobalEnv)



## ----join-bgc-----------------------------------------------------------------------------------------

# duplicate the 'horizon' information into a new table
S <- mgp_perhorizon

# duplicate the biogeochemical information into a new table
B <- mgp_perbiogeosample

# Select only 'Regular' samples (not audit)
B <- B[B$biogeoSampleType=="Regular" & 
         !is.na(B$biogeoSampleType),]

# Join biogeochem data to horizon data
S <- left_join(S, B, by=c('horizonID', 'siteID',
                          'pitID','setDate',
                          'collectDate',
                          'domainID',
                          'horizonName'))
S <- arrange(S, siteID, horizonTopDepth)



## ----site-labels--------------------------------------------------------------------------------------

## combine 'domainID' and 'siteID' into a new label variable
S$siteLabel=paste(S$domainID, S$siteID, sep="-")


# init SPC
depths(S) <- siteLabel ~ horizonTopDepth + horizonBottomDepth
```

Corrupt SPC here:
```r
# move site-level attributes to @site
site(S) <- ~ siteID + pitNamedLocation.x + pitID + labProjID + laboratoryName + nrcsDescriptionID
```

View error here:
```
S[42, ]
```

**Comment by brownag** [comment]
Narrowed the error condition (SPC validity method returns FALSE) down to inclusion of `labProjID` and/or `laboratoryName` in the `site<-` (formula) normalization call

That is: 

```
site(S) <- ~ siteID + pitNamedLocation.x + pitID + nrcsDescriptionID
S[42,]
```
works as expected.

The levels of those attributes do not quite do what they are supposed to with `site<-` -- we are getting duplication of some `siteLabel` values in site table. Accessing any of the row indices that is duplicated (4, 5, 28, 29, 32, 33, 42, 43 etc.) will produce an invalid SPC (because multiple profile IDs are matched)

![image](https://user-images.githubusercontent.com/20842828/99592022-7046de00-29a4-11eb-89a1-0d5a0632b096.png)

If we look at shared attributes between `S` and `B` (input data tables) we find that we need to probably separate the preparation of horizon data for promotion to SPC from the creation of a unique set of site data (that can be joined via `site<-`)

**Comment by brownag** [comment]
We should add some checks to `site<- ~` to make sure it does not allow for this

I would love to work up a proper example for #172 that also pulls in some pertinent information from our databases (SSURGO from SDA).
