### ISSUE TITLE
.data.frame.j question

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#176]
As I was working with some `data.table` objects today, I took another look at `.data.frame.j`. I'm probably missing something important here, but why is all of the taking-apart / re-assembly required, when a simple `..` could suffice?

```r
library(aqp)
library(data.table)
library(tibble)

# example data
df <- data.frame(a = letters[1:3], b = 2, c = 3)
dt <- data.table(df)
tb <- tibble(df)

# variables to subset / re-order via j-index
vars <- c('c', 'a', 'b')

# manual tests
df[, vars, drop = FALSE]
tb[, vars]
dt[, ..vars]

# overly simplistic and likely too specific, but why not?
.safeJ <- function(x, v) {
  # have to use special syntax here
  if(is.data.table(x)) {
    x <- x[, ..v]
  } else {
    # data.frame knows what to do
    # tibble seems to safely ignore `drop`
    x <- x[, v, drop = FALSE]
  }
  
  return(x)
}

# seems to work
.safeJ(df, vars)
.safeJ(dt, vars)
.safeJ(tb, vars)
```

I suppose the only thing (?) missing from this simpler function is an explicit ability to select out output object class. Class-in = class-out seems reasonable enough to not require an additional argument though?

**Comment by brownag** [comment]
Originally all of those methods were deliberately written to _avoid_ using any specific functionality from data.table (`..`) and tibble. This was perhaps an extreme example that should have been corrected and I think I actually mentioned it to you several weeks ago that there were several other ways to do the j-column subsetting now that we are actually bringing in data.table proper. 

I think that we could definitely do this, we of course would need to import `..` and `is.data.table`. I was planning on doing something with `eval` and avoiding `..` altogether.

**Comment by brownag** [comment]
To your point about not using the additional argument -- that will require a good amount of refactoring but is not impossible. "

Currently there are cases where 'data.frame' are converted to the target object (matching SPC) using `.data.frame.j(new.data.frame)` and `aqp_df_class(spc)`.

**Comment by brownag** [comment]
In d4c6cbb I implement something that properly uses data.table and appeases R CMD CHECK.

So, `..v` in your example "works" but upsets R CMD CHECK because `..v` is not defined. If you define it using the conventional `foo <- NULL` then it upsets {data.table}. So, the way to supply a vector of column names and get a subset data.frame is to use the special `.SD` syntax and the `.SDcols` argument. 

Regarding the `use_class` argument to `.data.frame.j` -- I made it so the default is `class(x)[1]` where `x` is the input `data.frame`. This allows for current implementation where `.data.frame.j` is used as a single step to get a class-conformal object while being to use for typical conditions.

**Comment by dylanbeaudette** [comment]
Thanks for looking into this and for the recent commit. Good idea on the default `use_class` argument.
