### ISSUE TITLE
reasonable replacement of NA or same top/bottom horizon depths

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/aqp#198]
I've split this off from #173, as it deals more with routine data cleaning vs. pure aesthetics.

After discussion all around, I'd suggest that the horizon depth "fixes" currently in soilDB be abstracted into a new function which would accomplish the following:
 1. replace `NA` in missing lower horizon depths → offset via argument
 2. replace bottom depths when `top == bottom` → offset via argument
 3. ~extend lower horizon depths when bottom-most horizon is too thin  → threshold and offset via argument (much less favorable in this context / issue and really belongs to #173)~

Possible function names: `fixMissingHzDepths`, `repairMissingDepths`, `repairMissingHzDepths` (used for now)

Code from {soilDB} was originally re-factored in this [commit](https://github.com/ncss-tech/aqp/commit/16344ef889308b685620266536bb3e6c9858ab04#diff-84d52f4df11a41f6586dca3ac327c0ac0eb8545d20262f248d463249ae59430c).

Issue should be closed with merge of #199

**Comment by dylanbeaudette** [comment]
The new version of `slice` cannot tolerate horizons out of order or depth logic errors and will depend on this new function. #115

**Comment by dylanbeaudette** [comment]
This function would also be an alternative to a long-standing (but now ill-conceived) approach in the OSD parsing code which adds 1cm to lower horizons that are missing a bottom depth.

**Comment by brownag** [comment]
I would drop number 3 off here, and address in the other issue, possibly as its own function, and maybe addressing the "painting" idea I brought up too. I think that one should be offered purely as an aesthetic because of the issues with Series Control Section. In particular for actual soil horizons versus bedrock layers... but also e.g. Cr v.s. R has different considerations w.r.t SCS. I think the other issue #173 and the comments made on discuss that case, and it should be addressed there not here.

I take some issue with these things (~like number 3) being applied _without_ context of horizon designation / in lieu texture / description "context". The categorical concepts require at least a basic conception of relevant metadata/levels etc. We do have some tools for this in aqp, thanks to you and @smroecker, but I am not sure where all that stuff is at and working up some demos and harmonization with SPC metadata options would be worthwhile for those of us who have not been involved in the development of that functionality so much.

I personally I want to see less and less of the heuristics in aqp proper. In my mind, aqp provides the tools to do it and document it (i.e. `generalize.hz()`) but actually doing it e.g.  `estimatePSCS` or `mollic.epipedon.thickness` is more of an _application_ of an algorithm than an algorithm itself. 

With my experience in this realm since 2017 or so I am leaning towards removing/moving to sharpshootR functions that heavily rely on that sort of heuristic internally, or otherwise making their assumptions painstakingly explicit to the user. This has always been my "goal"--despite the many different attempts of varying degrees of quality at wrangling logic and criteria- all are "incomplete" compared to more rigorous and semantically defined concepts of evaluating these things that fully account for data model differences.

Either that, or all of these need to allow for regex pattern matching for handling of cases, since we do support hzdesgnname metadata, and we seem to have at least tacitly accepted that as a commonly useful heuristic for "generic" pedon data/horizon designations. I feel like we oscillate back and forth on what exactly the extent of this the functions in aqp, and what is the purview of the analyst.  Thoughts?

This is demonstrated [conceptually] here for fixing old-style O horizons: https://github.com/ncss-tech/aqp/blob/master/misc/sandbox/fixOhorizons.R

To be clear -- I never intended this scratch code to become a function in aqp, but rather a simple application of a more generalized `checkHzDepthLogic`. I did think that it might feed into some of the new soilDB functions, and perhaps those will be in aqp all or in part. Proposed changes to itemize specific horizon errors and target them via an optional argument would enable making this type of function -- be it in one of our packages or in a user script -- extremely easy.

**Comment by dylanbeaudette** [comment]
100% agree, dropping item 3 as something that will be addressed in #173.

**Comment by dylanbeaudette** [comment]
> I personally I want to see less and less of the heuristics in aqp proper. In my mind, aqp provides the tools to do it and document it (i.e. `generalize.hz()`) but actually doing it e.g. `estimatePSCS` or `mollic.epipedon.thickness` is more of an _application_ of an algorithm than an algorithm itself.
> 
> With my experience in this realm since 2017 or so I am leaning towards removing/moving to sharpshootR functions that heavily rely on that sort of heuristic internally, or otherwise making their assumptions painstakingly explicit to the user. This has always been my "goal"--despite the many different attempts of varying degrees of quality at wrangling logic and criteria- all are "incomplete" compared to more rigorous and semantically defined concepts of evaluating these things that fully account for data model differences.
> 
> Either that, or all of these need to allow for regex pattern matching for handling of cases, since we do support hzdesgnname metadata, and we seem to have at least tacitly accepted that as a commonly useful heuristic for "generic" pedon data/horizon designations. I feel like we oscillate back and forth on what exactly the extent of this the functions in aqp, and what is the purview of the analyst. Thoughts?

Agreed. Heuristics should be a last resort at the algorithm level. We can and should explore that in a new issue though.
