### ISSUE TITLE
stop at line 614 from SoilProfileCollection-methods.R is a problem

### ISSUE THREAD

**Issue by smroecker** [ncss-tech/aqp#26]
The check if(! all(profile_id(res) == site(res)[[idname(res)]])) is a problem. Their are situations in NASIS where multiple sites are linked to one pedon.

for some reason its failing when I try and replace the horizons in an spc object, horizons(l) <- lh

[spc_error.zip](https://github.com/ncss-tech/aqp/files/781495/spc_error.zip)

well I think I figured it out
the used merge() instead of join()
which changes the order of the column names
horizons(l) <- lh must not like that

**Comment by dylanbeaudette** [comment]
Thanks for reporting this.

While it may be an issue with data extracted from NASIS, this isn't really an `aqp` issue: the `SoilProfileCollection` data structure imposes the rule: 1 row of site data per `profile_id`. I would suggest opening this issue as a feature request for `soilDB`, or suggest how this implementation might work in `aqp`. At the moment there are no plans for supporting multiple rows in @site per ID. That said, multiple pedons / site isn't really a problem because each pedon will have its own unique `peiid` and the site data will be duplicated.

**Comment by dylanbeaudette** [comment]
The proposed SPC structure in 2.0 will at least be able to enforce consistency within a single `SoilProfile`.

**Comment by dylanbeaudette** [comment]
This is related to #105 in that every use of `merge()` in `aqp` 1.x that affects site or horizon attributes must include the `sort=FALSE` argument.
